### ISSUE TITLE
Strange lines in toplevel CmakeLists.txt

### ISSUE THREAD

**Issue by wkazubski** [bistromath/gr-air-modes#107]
Toplevel CmakeLists.txt contains following lines:
...
set(GR_INCLUDE_DIR      include/foo)
set(GR_CMAKE_DIR        ${CMAKE_MODULES_DIR}/foo)
...
probably gr-air-modes should be here.

**Comment by bistromath** [comment]
Fixed, thanks for letting me know. Does it build and run for you? The current master has very limited testing right now.
