### ISSUE TITLE
No module modes_rx_ui (required by modes_gui)

### ISSUE THREAD

**Issue by yarda** [bistromath/gr-air-modes#30]
$ modes_gui
Traceback (most recent call last):
  File "/usr/bin/modes_gui", line 30, in <module>
    from air_modes.modes_rx_ui import Ui_MainWindow
ImportError: No module named modes_rx_ui

The code:
from air_modes.modes_rx_ui import Ui_MainWindow

The grep for Ui_MainWindow against sources provides no match.

**Comment by navyashreehc** [comment]
$ modes_gui
Traceback (most recent call last):
File "/usr/bin/modes_gui", line 30, in 
from air_modes.modes_rx_ui import Ui_MainWindow
ImportError: No module named modes_rx_ui


Please provide some suggestions for this problem
