### ISSUE TITLE
function parseBDS09_1(data) in parse.py is not correct?

### ISSUE THREAD

**Issue by chenggiant** [bistromath/gr-air-modes#54]
> ns_vel = float(data["vns"])
> ew_vel = float(data["vew"])

Should we minus 1?

> ns_vel = float(data["vns"]) - 1
> ew_vel = float(data["vew"]) -1

**Comment by bistromath** [comment]
No. See DO-260B 2.2.8.1.8 and 2.2.8.1.9.
