### ISSUE TITLE
No Location data

### ISSUE THREAD

**Issue by SebastianBoyd** [bistromath/gr-air-modes#66]
I am successfully receiving data from aircraft but without any location data. I am exporting all the data to a kml but no aircraft locations are shown or printed in the console. I live under a flight path so it is not a problem with the signal.

**Comment by bistromath** [comment]
Where are you? Are you seeing any Type 17 packets come in? Can you cut and
paste a received capture? Are you using a decent antenna with a clear view
of the sky (nothing at all in between you and the aircraft)?

**Comment by SebastianBoyd** [comment]
I will do some more testing later and reply with the results. Where can I find a list of the meanings of the package types?
