### ISSUE TITLE
CMake Error at CMakeLists.txt

### ISSUE THREAD

**Issue by imashok7** [bistromath/gr-air-modes#77]
i have been working on the same code in UBUNTU 15.04 VERSION.
now i have been encountering the problem .i have sent the image of the error. so plz do help.
also inform is it works on rtl-sdr 2382u device
![screenshot from 2015-11-03 13_29_41](https://cloud.githubusercontent.com/assets/13936901/10903504/74bf8f96-8232-11e5-868d-06855e469f21.png)

**Comment by bistromath** [comment]
Have you installed Gnuradio?

**Comment by imashok7** [comment]
ya i have installed.

**Comment by bistromath** [comment]
Please give me more information-- what distribution, Gnuradio version, how
GR was installed, where GR was installed.

**Comment by imashok7** [comment]
sir,
i have install gnuradio from gnuradio 3.7.8 tar.gz file

i have tried from build script but i got error. (libzmq file error)
i have ubuntu 15.04 on my laptop
