### ISSUE TITLE
Map interface no longer works

### ISSUE THREAD

**Issue by devnulling** [bistromath/gr-air-modes#83]
The Google Map display appears to no longer work.

Getting this error in the console:

file:///tmp/mode_s.html line 120: ReferenceError: Can't find variable: MarkerWithLabel

Google Maps appears to require an API key now, and this script 404's when it's trying to be loaded - http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerwithlabel/1.1.9/src/markerwithlabel.js

**Comment by devnulling** [comment]
I've submitted PR #84 that fixes this issue.

**Comment by bistromath** [comment]
A pull request! Thanks!

**Comment by sbmueller** [comment]
The map interface does not work for me as well. Error is:
`http://maps.google.com/maps/api/js?key=None line 32: Google Maps API error: InvalidKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key-map-error`

**Comment by devnulling** [comment]
@sbmueller You need to register for an API key with Google Maps API @ https://developers.google.com/maps/documentation/javascript/ and put it into the API key field.
